; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env6,@env9,@env10 ; 00 : guiatr
	.word @env3,@env1,@env2,@env0 ; 01 : guitar2
	.word @env4,@env6,@env8,@env0 ; 02 : bass
	.word @env5,@env6,@env2,@env0 ; 03 : drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$02,$b4,$02,$c0,$02,$b4,$02,$c0,$02,$b4,$00,$0a
@env2:
	.byte $c3,$7f,$00,$00
@env3:
	.byte $00,$cc,$7f,$00,$02
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $00,$cf,$cd,$ca,$c1,$c0,$c0,$00,$04
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$00,$05
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c1,$7f,$00,$00
@env10:
	.byte $00,$c2,$c1,$c0,$00,$03

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $05, $95, $08, $95, $0c, $95, $14, $95, $11, $a1, $00, $a1, $13, $95, $00, $95, $11, $95, $0f, $95, $00, $95, $0f, $95
	.byte $00, $ad, $05, $95, $48
	.byte $41, $15
	.word @song0ref6
	.byte $c5, $03, $95, $05, $95, $48
	.byte $41, $1c
	.word @song0ref6
	.byte $48
	.byte $41, $15
	.word @song0ref6
	.byte $c5, $03, $95, $05, $95, $48, $00, $ff, $ff, $fd, $48, $ff, $ff, $cf, $03, $95, $05, $95, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $97, $82
@song0ref81:
	.byte $24, $95, $2c, $95, $00, $95, $2c, $95, $29, $a1, $00, $89, $29, $95, $2b, $95, $00, $95, $2b, $95, $27, $a1, $00, $d1
	.byte $97
	.byte $41, $18
	.word @song0ref81
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $97, $84
@song0ref121:
	.byte $11, $89, $00, $89, $11, $95, $00, $95, $11, $95, $00, $ad, $11, $89, $00, $89, $0f, $95, $00, $95, $0f, $89, $00, $ff
	.byte $81, $97
	.byte $41, $1a
	.word @song0ref121
	.byte $41, $1a
	.word @song0ref121
	.byte $41, $1a
	.word @song0ref121
	.byte $41, $1a
	.word @song0ref121
	.byte $41, $19
	.word @song0ref121
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $86
@song0ref167:
	.byte $14, $95, $00, $95, $16, $95, $14, $89, $00, $89, $14, $95, $00, $95, $16, $95, $14, $95, $00, $95, $14, $89, $00, $89
	.byte $16, $ad, $00, $ad, $16, $95, $14, $95
	.byte $41, $20
	.word @song0ref167
	.byte $41, $20
	.word @song0ref167
	.byte $41, $20
	.word @song0ref167
	.byte $41, $20
	.word @song0ref167
	.byte $41, $20
	.word @song0ref167
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref218:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $09
	.word @song0ref218
	.byte $42
	.word @song0ch4loop
